export const WINDOW_BOMBCRYPTO_IFRAME_WIDTH = 960;
export const WINDOW_BOMBCRYPTO_IFRAME_HEIGHT = 642;

export const WINDOW_BOMBCRYPTO_WIDTH = WINDOW_BOMBCRYPTO_IFRAME_WIDTH;
export const WINDOW_BOMBCRYPTO_TOOL_BAR_HEIGHT = 40;
// export const WINDOW_BOMBCRYPTO_HEIGHT = WINDOW_BOMBCRYPTO_IFRAME_HEIGHT + WINDOW_BOMBCRYPTO_TOOL_BAR_HEIGHT;
export const WINDOW_BOMBCRYPTO_HEIGHT = WINDOW_BOMBCRYPTO_IFRAME_HEIGHT;
